#!/usr/bin/env node
/**
 * garden-mcp — Model Context Protocol server for building Zendesk apps with
 * the Zendesk Garden design system (@zendeskgarden/react-*).
 *
 * Data comes from data/components.json (generated by scripts/build-catalog.mjs
 * from github.com/zendeskgarden/react-components). Everything is local and
 * offline; rebuild the catalog to bump the Garden version.
 *
 * Tools:
 *   garden_list_components  overview of every package + its components
 *   garden_get_component    npm/install + exports + full props (JSDoc) + README
 *   garden_search           keyword search across names, props and READMEs
 *   garden_theming          required ThemeProvider / theming / a11y setup
 *   garden_app_setup        ZAF v2 + React + Garden bootstrapping recipe
 */
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';

const __dirname = dirname(fileURLToPath(import.meta.url));
const catalog = JSON.parse(await readFile(join(__dirname, 'data', 'components.json'), 'utf8'));
const PKGS = catalog.packages;
const PKG_LIST = Object.values(PKGS);

// ---- resolution helpers ---------------------------------------------------

/** component/package/npm name (any case) -> package record */
function resolve(name) {
  const q = String(name || '').trim().toLowerCase();
  if (!q) return null;
  // exact package key or npm name
  for (const p of PKG_LIST) {
    if (p.package.toLowerCase() === q) return { pkg: p, component: null };
    if (p.npm.toLowerCase() === q) return { pkg: p, component: null };
    if (`react-${p.package}`.toLowerCase() === q) return { pkg: p, component: null };
  }
  // exact component match (e.g. "Button", "Accordion.Section" -> "Accordion")
  const base = q.split('.')[0];
  for (const p of PKG_LIST) {
    for (const c of p.components) {
      if (c.toLowerCase() === q || c.toLowerCase() === base) return { pkg: p, component: c };
    }
  }
  // fuzzy: component startsWith / includes
  for (const p of PKG_LIST) {
    for (const c of p.components) {
      if (c.toLowerCase().startsWith(base)) return { pkg: p, component: c };
    }
  }
  return null;
}

function installCmd(p) {
  const peers = Object.keys(p.peerDependencies || {}).join(' ');
  return `npm install ${p.npm}` + (peers ? `\n# peer deps (also required):\nnpm install ${peers}` : '');
}

function text(t) { return { content: [{ type: 'text', text: t }] }; }

// ---- server ---------------------------------------------------------------

const server = new McpServer({ name: 'garden-mcp', version: '0.1.0' });

server.registerTool(
  'garden_list_components',
  {
    title: 'List Garden packages & components',
    description:
      `List every Zendesk Garden package (Garden ${catalog.gardenVersion}) with its exported components and a one-line "when to use". ` +
      'Call this first to discover which package/component fits the UI you need before writing code. Optional query filters by name/summary.',
    inputSchema: { query: z.string().optional().describe('Optional keyword to filter packages/components (e.g. "select", "table", "loading")') }
  },
  async ({ query }) => {
    const q = (query || '').toLowerCase();
    const rows = PKG_LIST
      .filter(p => !q || `${p.package} ${p.summary} ${p.components.join(' ')}`.toLowerCase().includes(q))
      .map(p => `### ${p.npm}\n${p.summary}\ncomponents: ${p.components.join(', ') || '(none)'}\ndocs: ${p.docs}`);
    const header = `Zendesk Garden ${catalog.gardenVersion} — ${PKG_LIST.length} packages` +
      (q ? ` (filtered by "${query}")` : '') +
      `\nEvery Garden app must wrap its tree in <ThemeProvider> (garden_theming).\n`;
    return text(header + '\n' + (rows.join('\n\n') || 'No matches.'));
  }
);

server.registerTool(
  'garden_get_component',
  {
    title: 'Get a Garden component (props, imports, examples)',
    description:
      'Get everything needed to use a Garden component or package: npm name, install command, all exported components, ' +
      'the full prop interfaces (TypeScript source with JSDoc, authoritative) and the README usage examples. ' +
      'Accepts a component name ("Button", "Accordion"), a package key ("buttons") or an npm name ("@zendeskgarden/react-forms").',
    inputSchema: {
      name: z.string().describe('Component, package, or npm name — e.g. "Button", "forms", "@zendeskgarden/react-modals"'),
      include: z.enum(['all', 'props', 'readme']).optional().describe('Limit output: "props" (interfaces only), "readme" (examples only), or "all" (default)')
    }
  },
  async ({ name, include = 'all' }) => {
    const hit = resolve(name);
    if (!hit) {
      const names = PKG_LIST.flatMap(p => p.components).sort();
      return text(`No Garden component/package matched "${name}".\nKnown components: ${names.join(', ')}`);
    }
    const p = hit.pkg;
    let out = `# ${p.npm}${p.version ? ` @ ${p.version}` : ''}\n${p.summary}\n`;
    if (hit.component) out += `\nMatched component: **${hit.component}** (siblings: ${p.components.join(', ')})\n`;
    out += `\n## Install\n\`\`\`sh\n${installCmd(p)}\n\`\`\`\n`;
    out += `\n## Exports\ncomponents: ${p.components.join(', ') || '(none)'}\ntypes: ${p.typeExports.join(', ') || '(none)'}\n`;
    if (include === 'all' || include === 'props') {
      out += `\n## Props (source of truth — src/types/index.ts)\n\`\`\`ts\n${p.props.trim() || '(no explicit prop types)'}\n\`\`\`\n`;
    }
    if (include === 'all' || include === 'readme') {
      out += `\n## README (usage & examples)\n${p.readme.trim() || '(no README)'}\n`;
    }
    out += `\nDocs: ${p.docs}`;
    return text(out);
  }
);

server.registerTool(
  'garden_search',
  {
    title: 'Search the Garden catalog',
    description:
      'Full-text search across Garden component names, prop names/JSDoc and README examples. ' +
      'Use when you know a behavior or prop (e.g. "isDisabled", "validation message", "drag and drop", "toast") but not the component.',
    inputSchema: {
      query: z.string().describe('Keyword or phrase, e.g. "async loading", "isInvalid", "menu keyboard"'),
      limit: z.number().int().min(1).max(20).optional().describe('Max packages to return (default 6)')
    }
  },
  async ({ query, limit = 6 }) => {
    const q = query.toLowerCase();
    const scored = PKG_LIST.map(p => {
      const hay = { name: `${p.package} ${p.npm} ${p.components.join(' ')}`.toLowerCase(), props: p.props.toLowerCase(), readme: p.readme.toLowerCase(), sum: p.summary.toLowerCase() };
      let score = 0;
      if (hay.name.includes(q)) score += 10;
      if (hay.sum.includes(q)) score += 5;
      if (hay.props.includes(q)) score += 3;
      if (hay.readme.includes(q)) score += 1;
      return { p, score };
    }).filter(x => x.score > 0).sort((a, b) => b.score - a.score).slice(0, limit);

    if (!scored.length) return text(`No matches for "${query}". Try garden_list_components to browse.`);
    const snippet = (p) => {
      const src = (p.props + '\n' + p.readme).split('\n');
      const i = src.findIndex(l => l.toLowerCase().includes(q));
      if (i < 0) return '';
      return '\n  …' + src.slice(Math.max(0, i - 1), i + 2).map(s => s.trim()).filter(Boolean).join(' / ') + '…';
    };
    return text(`Matches for "${query}":\n\n` + scored.map(({ p }) =>
      `- **${p.components[0] || p.package}** (${p.npm}) — ${p.summary}${snippet(p)}\n  → garden_get_component name:"${p.components[0] || p.package}"`
    ).join('\n\n'));
  }
);

server.registerTool(
  'garden_theming',
  {
    title: 'Garden theming & accessibility setup',
    description:
      'How to wrap an app in ThemeProvider, read semantic colors with getColor, support dark mode / RTL, and keep focus rings accessible. ' +
      'Read this before building any Garden UI — components are unstyled/broken without a ThemeProvider.',
    inputSchema: {}
  },
  async () => {
    const t = PKGS.theming;
    return text(
`# Garden theming (${t.npm} @ ${t.version})

Every Garden component needs a theme. Wrap the whole app once, at the root.

\`\`\`jsx
import { ThemeProvider, DEFAULT_THEME } from '@zendeskgarden/react-theming';

<ThemeProvider theme={DEFAULT_THEME}>
  <App />
</ThemeProvider>
\`\`\`

## Semantic colors (don't hardcode hex)
\`\`\`js
import { getColor } from '@zendeskgarden/react-theming';
const fg = getColor({ theme, variable: 'foreground.default' });
const border = getColor({ theme, variable: 'border.default' });
// families: foreground.{default,subtle,primary,success,danger,warning}
//           background.{default,subtle,...}  border.{default,subtle,...}
\`\`\`

## Dark mode
\`\`\`jsx
<ThemeProvider theme={{ ...DEFAULT_THEME, colors: { ...DEFAULT_THEME.colors, base: 'dark' } }}>
\`\`\`

## RTL
Set \`rtl: true\` on the theme (\`{ ...DEFAULT_THEME, rtl: true }\`) — Garden flips layout automatically.

## Rendering into another document/iframe
Pass \`focusVisibleRef\` / \`theme.document\` when the app lives in an iframe so focus-visible and portals target the right document. \`useDocument(theme)\` returns the active document.

## Accessibility
- Garden ships WCAG-compliant focus rings; never remove outlines.
- Provide accessible labels: \`aria-label\` on IconButton, \`<Field.Label>\` on inputs.
- Keep the \`ThemeProvider\` at the true root so portals (Modal, Tooltip, Menu) inherit it.

## Prop reference (theming exports)
components/utilities: ${t.components.join(', ')}
\`\`\`ts
${t.props.trim()}
\`\`\`
Docs: ${t.docs}`);
  }
);

server.registerTool(
  'garden_app_setup',
  {
    title: 'Zendesk app + React + Garden bootstrap',
    description:
      'End-to-end recipe for a Zendesk Support app (ZAF v2) rendered with React + Garden: manifest locations, iframe entry, ZAFClient, ' +
      'auto-resize, and where the ThemeProvider goes. Use when scaffolding a new app or adding Garden to an existing ZAF app.',
    inputSchema: {}
  },
  async () => text(
`# Zendesk app (ZAF v2) + React + Garden

## 1. manifest.json — declare locations (iframe entry per location)
\`\`\`json
{
  "location": { "support": {
    "ticket_sidebar": { "url": "assets/iframe.html", "flexible": true }
  }},
  "frameworkVersion": "2.0"
}
\`\`\`

## 2. assets/iframe.html — load the ZAF SDK, then your bundle
\`\`\`html
<script src="https://static.zdassets.com/zendesk_app_framework_sdk/2.0/zaf_sdk.min.js"></script>
<div id="root"></div>
<script src="app.js"></script>
\`\`\`

## 3. app entry — ZAFClient + React + Garden ThemeProvider
\`\`\`jsx
import ZAFClient from 'zendesk_app_framework_sdk'; // global provided by zaf_sdk
import { createRoot } from 'react-dom/client';
import { ThemeProvider } from '@zendeskgarden/react-theming';

const client = ZAFClient.init();
client.invoke('resize', { width: '100%', height: '400px' }); // fit the iframe

createRoot(document.getElementById('root')).render(
  <ThemeProvider>
    <App client={client} />
  </ThemeProvider>
);
\`\`\`

## 4. Talk to Zendesk through the client
\`\`\`js
const { ticket } = await client.get('ticket');            // read
await client.set('ticket.comment.text', 'Hello');          // write
client.on('ticket.status.changed', s => { /* ... */ });    // events
\`\`\`

## 5. Auto-resize to content (sidebar/editor apps)
Observe the body height and call \`client.invoke('resize', ...)\` on change, or set \`"flexible": true\` in the manifest location.

## Build
Bundle the React app to \`assets/app.js\` (esbuild/webpack). Garden needs \`styled-components\` as a peer dep. Validate/package with \`zcli apps:validate .\` / \`zcli apps:package .\`.

Notes:
- Put exactly one \`ThemeProvider\` at the root; Modal/Tooltip/Menu portals inherit it.
- Full-page (nav_bar / modal) apps: use @zendeskgarden/react-chrome for the shell.
- Icons: \`@zendeskgarden/svg-icons\` (import an SVG and render it inside Button.StartIcon etc.).`)
);

await server.connect(new StdioServerTransport());
console.error(`garden-mcp ready — Garden ${catalog.gardenVersion}, ${PKG_LIST.length} packages.`);
